In [1]:
# imports
import pandas as pd
import numpy as np
import functools
from functools import reduce

In [2]:
# read data
albumin = pd.read_csv('./cleaned_data/albumin.csv')
bp = pd.read_csv('./cleaned_data/bp.csv')
cholestrol = pd.read_csv('./cleaned_data/cholestrol.csv')
creatnine = pd.read_csv('./cleaned_data/creatnine.csv')
creatnine_clearance = pd.read_csv('./cleaned_data/creatnine_clearance.csv')
demo = pd.read_csv('./cleaned_data/demographics.csv')

In [3]:
glycemia = pd.read_csv('./cleaned_data/glycemia.csv')
hdl = pd.read_csv('./cleaned_data/hdl.csv')
height = pd.read_csv('./cleaned_data/height.csv')
hemoglobin = pd.read_csv('./cleaned_data/hemoglobin.csv')
ldl = pd.read_csv('./cleaned_data/ldl.csv')
triglycerides = pd.read_csv('./cleaned_data/triglycerides.csv')
weight = pd.read_csv('./cleaned_data/weight.csv')

In [4]:
diag = pd.read_csv('./cleaned_data/diag_cvd.csv')

In [5]:
albumin = albumin.drop(columns=["Unnamed: 0", "microalbuminuria_date"])
bp = bp.drop(columns=["Unnamed: 0", "blood_pressure_date"])
cholestrol = cholestrol.drop(columns=["Unnamed: 0", "cholesterol_date"])
creatnine = creatnine.drop(columns=["Unnamed: 0", "creatinine_date"])
creatnine_clearance = creatnine_clearance.drop(columns=["Unnamed: 0", "creatinine_clearance_date"])
demo = demo.drop(columns=["Unnamed: 0", "IGNORE_THIS_COLUMN_1", "IGNORE_THIS_COLUMN_2", "DVP_REG_CODE", "DVP_PRO_CODEO", "TYPE_USER"])
diag = diag.drop(columns=["Unnamed: 0", "Diagnosis_Date"])
glycemia = glycemia.drop(columns=["Unnamed: 0", "glycemia_date"])
hdl = hdl.drop(columns=["Unnamed: 0", "HDL_high-density_lipoprotein_date"])
height = height.drop(columns=["Unnamed: 0", "height_date"])
hemoglobin = hemoglobin.drop(columns=["Unnamed: 0", "glycated_hemoglobin_date"])
ldl = ldl.drop(columns=["Unnamed: 0", "LDL_low-density_lipoprotein_date"])
triglycerides = triglycerides.drop(columns=["Unnamed: 0", "triglycerides_date"])
weight = weight.drop(columns=["Unnamed: 0", "weight_date"])

In [6]:
albumin = albumin.drop_duplicates(subset=['PK_PATIENT'], keep='last')
bp =bp.drop_duplicates(subset=['PK_PATIENT'], keep='last')
cholestrol = cholestrol.drop_duplicates(subset=['PK_PATIENT'], keep='last')
creatnine = creatnine.drop_duplicates(subset=['PK_PATIENT'], keep='last')
creatnine_clearance = creatnine_clearance.drop_duplicates(subset=['PK_PATIENT'], keep='last')
demo = demo.drop_duplicates(subset=['PK_PATIENT'], keep='last')
diag = diag.drop_duplicates(subset=['PK_PATIENT'], keep='last')
glycemia = glycemia.drop_duplicates(subset=['PK_PATIENT'], keep='last')
hdl = hdl.drop_duplicates(subset=['PK_PATIENT'], keep='last')
height = height.drop_duplicates(subset=['PK_PATIENT'], keep='last')
hemoglobin = hemoglobin.drop_duplicates(subset=['PK_PATIENT'], keep='last')
ldl = ldl.drop_duplicates(subset=['PK_PATIENT'], keep='last')
triglycerides = triglycerides.drop_duplicates(subset=['PK_PATIENT'], keep='last')
weight = weight.drop_duplicates(subset=['PK_PATIENT'], keep='last')

In [7]:
frames = [albumin, bp, cholestrol, creatnine, creatnine_clearance, demo, diag, glycemia, 
         hdl, height, hemoglobin, ldl, triglycerides, weight]

df_final = functools.reduce(lambda left,right: pd.merge(left,right,on='PK_PATIENT'), frames)

In [8]:
# demo = demo.sample(frac=.1, random_state=1)
# diag = diag.sample(frac=.1, random_state=1)
# bp = bp.sample(frac=.1, random_state=1)
# weight = weight.sample(frac=.1, random_state=1)
# height = height.sample(frac=.1, random_state=1)
# albumin = albumin.sample(frac=.1, random_state=1)
# cholestrol = cholestrol.sample(frac=.1, random_state=1)
# creatnine = creatnine.sample(frac=.1, random_state=1)
# creatnine_clearance = creatnine_clearance.sample(frac=.1, random_state=1)
# glycemia = glycemia.sample(frac=.1, random_state=1)
# hdl = hdl.sample(frac=.1, random_state=1)
# ldl = ldl.sample(frac=.1, random_state=1)
# hemoglobin = hemoglobin.sample(frac=.1, random_state=1)
# triglycerides = triglycerides.sample(frac=.1, random_state=1)

In [9]:
df_final

,PK_PATIENT,microalbuminuria,systolic,diastolic,cholesterol,creatinine,creatinine_clearance,BIRTH_DATE,DEATH_DATE,AGE,SEX,CENTER_ID,Diagnosis_Code,glycemia,HDL_high-density_lipoprotein,height,glycated_hemoglobin,LDL_low-density_lipoprotein,triglycerides,weight
0,0,4.96,120.0,80.0,239,0.92,1.97,2020/11/28,1900/01/01,1,FEMALE,325,I10X,85,51,-1.0,6.9,73,219,80.0
1,10,5.37,120.0,80.0,148,1.01,7.14,1950/05/17,1900/01/01,72,MALE,92,E105,97,34,175.0,6.6,89,180,-1.0
2,12,9.35,110.0,70.0,127,0.59,8.43,1951/07/26,1900/01/01,71,FEMALE,92,E121,112,46,-1.0,7.3,68,140,-1.0
3,16,5.13,118.0,72.0,192,0.77,8.83,1953/05/12,1900/01/01,69,FEMALE,92,E780,94,47,160.0,"5,7",108,180,-1.0
4,21,30.41,125.0,74.0,146,0.55,18.49,1947/04/30,2013/05/22,75,FEMALE,92,E785,88,35,165.0,6.1,148,165,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21286,1192030,5.75,120.0,80.0,198.0,0.65,7.18,1985/05/16,1900/01/01,37,FEMALE,151,E669,84.79,53.7,160.0,5.4,109.10,176.0,74.0
21287,1192145,0.83,120.0,70.0,185.2,0.60,2.13,1948/12/21,1900/01/01,73,FEMALE,69,E119,87,38.8,155.0,5.9,104.20,211.0,68.0
21288,1196064,4.55,120.0,80.0,110.4,0.92,11.77,1946/01/20,1900/01/01,76,FEMALE,69,E149,175,57.7,160.0,6.8,30.52,124.4,74.0
21289,1196331,2.83,100.0,60.0,172.6,1.04,3.05,1956/02/15,1900/01/01,66,FEMALE,52,E119,117,47.7,-1.0,6.3,104.38,102.6,81.0
21290,1199638,14.37,120.0,80.0,268,0.95,6.47,1966/12/01,1900/01/01,55,MALE,300,E785,97,36,-1.0,5.8,190,617,-1.0

In [10]:
df_final.to_csv(r'../cleaned_data/final_data.csv', sep=',', encoding='utf-8', header='true')